- hosts: webservers
  become: true
  gather_facts: no

  vars_files:
    - var.yaml
  
  tasks:
  - name: p3
    shell: sudo apt upgrade -y && sudo apt install python

  tasks:
  - name: Docker install
    shell: |
      if ! command -v docker;  then
        curl -fsSL https://get.docker.com/ -o get-docker.sh;
        sh get-docker.sh
      fi

  - name: remove old and unused Docker images
    shell: |
        if [ $(sudo  docker ps -aq | wc -l ) -gt 0 ]; then
          sudo docker rm -f $(sudo docker ps -qa)
          sudo docker rmi -f $(sudo docker images -q)
        fi  

  - name: Docker Pull
    shell: sudo docker pull shaym95/bootcamp:latest

  - name: add .env file
    shell: | 
      echo "
      # Host configuration
      PORT=8080
      HOST=0.0.0.0
      # Postgres configuration
      PGHOST={{pghost}}
      PGUSERNAME={{pg_username}}
      PGDATABASE=postgres
      PGPASSWORD={{pg_password}}
      PGPORT=5432
      HOST_URL=http://{{LB_ip}}:8080
      COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
      NODE_ENV=development
      # Okta configuration
      OKTA_ORG_URL={{okta_url}}
      OKTA_CLIENT_ID={{okta_client_id}}
      OKTA_CLIENT_SECRET={{okta_client_secret}}
      " > ~/.env;
    
    tags:
         - env

  - name: Run your image as a container 
    shell: sudo docker run --restart always -d -p 8080:8080 shaym95/bootcamp 
  
  - name: copy .env file to the container
    shell: docker cp ~/.env  $(sudo docker ps -aq):/usr/src/app/.env

  - name: restartthe container
    shell: docker restart $(sudo docker ps -aq)

  - name: run initdb script
    shell: docker exec $(sudo docker ps -aq) npm run initdb
    run_once: true